name: Build Python Package

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build-wheel:

    runs-on: ubuntu-latest

    steps:
    - run: echo "/root/.local/bin" >> $GITHUB_PATH
    - uses: actions/checkout@v3
    - name: Install poetry
      run: pipx install poetry
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: "poetry"
        cache-dependency-path: "python/pyproject.toml"
        
    - name: Install SemanticKernel
      run: cd python && poetry install --no-ansi
      
    - name: Build wheel
      run: poetry build  

    - name: Upload wheel file to artifacts
      uses: actions/upload-artifact@v3
      with:
        name: dist
        path: ./dist/*
